#!/bin/sh
#See https://help.ubuntu.com/community/AutomaticSecurityUpdates#Using_cron_and_aptitude
NAME=apt-security-updates
LOG="/var/log/${NAME}"
echo "----- ${NAME} run: $(date) -----" >> "${LOG}"
export DEBIAN_FRONTEND=noninteractive
apt-get install --quiet --yes aptitude >/dev/null 2>&1
aptitude --quiet update >> "${LOG}"
aptitude --quiet safe-upgrade -o Aptitude::Delete-Unused=false --assume-yes --target-release `lsb_release -cs`-security >> "${LOG}"
apt-get --quiet --yes autoremove
echo "Security updates (if any) installed. ${NAME} run completed" >> "${LOG}"
